// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.FSharp.Core;
using System.Collections.Generic;

namespace WorldConquest.PexTests
{
  public partial class GameStateUpdateTestsGenerated {
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
public void Test1811()
{
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[0][];
    int[][] intss = new int[0][];
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, intss);
}
  }
}
