// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.FSharp.Core;
using System.Collections.Generic;

namespace WorldConquest.PexTests
{
  public partial class GameStateUpdateTestsGenerated {
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
public void Test1811()
{
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[0][];
    int[][] intss = new int[0][];
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, intss);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
public void Test1491()
{
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    int[][] intss = new int[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[0];
    unitInfoss[0] = unitInfos;
    int[] ints = new int[0];
    intss[0] = ints;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, intss);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException183()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 0, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException566()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 1, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException984()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 2, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException604()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 3, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException929()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 4, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException908()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 4, true, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException927()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 7, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException346()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 8, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException859()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 8, true, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException268()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 10, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException98401()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 9, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException326()
{
    object o;
    global::Units.UnitInfo unitInfo;
    global::Units.UnitInfo unitInfo1;
    o = global::HexTilingFactory.CreateHexCoords(0, 4);
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)o, (float)0, 1, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    unitInfo1 = global::UnitsFactory.CreateUnitInfo
                    ((global::HexTiling.HexCoords)null, (float)0, 0, false, 
                     0, (global::Units.BomberTransport)null, 
                     (global::Units.CarriedAircraft[])null, 
                     (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[2];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    unitInfos[1] = unitInfo1;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void Test1915()
{
    object o;
    global::Units.UnitInfo unitInfo;
    global::Units.UnitInfo unitInfo1;
    o = global::HexTilingFactory.CreateHexCoords(0, 4);
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)o, (float)0, 1, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    unitInfo1 = global::UnitsFactory.CreateUnitInfo
                    ((global::HexTiling.HexCoords)o, (float)0, 0, false, 
                     0, (global::Units.BomberTransport)null, 
                     (global::Units.CarriedAircraft[])null, 
                     (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    int[][] intss = new int[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[2];
    unitInfoss[0] = unitInfos;
    int[] ints = new int[0];
    intss[0] = ints;
    unitInfos[0] = unitInfo;
    unitInfos[1] = unitInfo1;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, intss);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void Test1677()
{
    object o;
    global::Units.UnitInfo unitInfo;
    global::Units.UnitInfo unitInfo1;
    o = global::HexTilingFactory.CreateHexCoords(0, 5);
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)o, (float)0, 1, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    unitInfo1 = global::UnitsFactory.CreateUnitInfo
                    ((global::HexTiling.HexCoords)o, (float)0, 0, false, 
                     0, (global::Units.BomberTransport)null, 
                     (global::Units.CarriedAircraft[])null, 
                     (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    int[][] intss = new int[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[2];
    unitInfoss[0] = unitInfos;
    int[] ints = new int[0];
    intss[0] = ints;
    unitInfos[0] = unitInfo;
    unitInfos[1] = unitInfo1;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, intss);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException852()
{
    global::Units.UnitInfo unitInfo;
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 5, false, 
                    0, global::Units.BomberTransport.NewInfantry((global::Units.Health)null), 
                    (global::Units.CarriedAircraft[])null, 
                    (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException395()
{
    global::Units.UnitInfo unitInfo;
    global::Units.CarriedAircraft[] carriedAircrafts
       = new global::Units.CarriedAircraft[0];
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 6, false, 
                    0, (global::Units.BomberTransport)null, 
                    carriedAircrafts, (global::Units.TransportedUnit[])null);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
[TestMethod]
[PexGeneratedBy(typeof(GameStateUpdateTests))]
[PexRaisedException(typeof(NullReferenceException))]
public void Test1ThrowsNullReferenceException206()
{
    global::Units.UnitInfo unitInfo;
    global::Units.TransportedUnit[] transportedUnits
       = new global::Units.TransportedUnit[0];
    unitInfo = global::UnitsFactory.CreateUnitInfo
                   ((global::HexTiling.HexCoords)null, (float)0, 11, false, 
                    0, (global::Units.BomberTransport)null, 
                    (global::Units.CarriedAircraft[])null, transportedUnits);
    Tuple<global::HexTiling.HexCoords, 
          global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[] tuples
       = new Tuple<global::HexTiling.HexCoords, 
                   global::Resource.Resource, FSharpOption<global::GameState.PlayerId>>[0];
    global::Units.UnitInfo[][] unitInfoss = new global::Units.UnitInfo[1][];
    global::Units.UnitInfo[] unitInfos = new global::Units.UnitInfo[1];
    unitInfoss[0] = unitInfos;
    unitInfos[0] = unitInfo;
    ((GameStateUpdateTests)this).Test1(tuples, unitInfoss, (int[][])null);
}
  }
}
